export const flagsListConstants = {
  FETCH_FLAGS_LIST_WAITING: 'FETCH_FLAGS_LIST_WAITING',
  FETCH_FLAGS_LIST_SUCCESS: 'FETCH_FLAGS_LIST_SUCCESS',
  FETCH_FLAGS_LIST_FAIL: 'FETCH_FLAGS_LIST_FAIL',

  FETCH_SENT_FLAGS_WAITING: 'FETCH_SENT_FLAGS_WAITING',
  FETCH_SENT_FLAGS_SUCCESS: 'FETCH_SENT_FLAGS_SUCCESS',
  FETCH_SENT_FLAGS_FAIL: 'FETCH_SENT_FLAGS_FAIL',
  
  FETCH_PUBLIC_FLAGS_WAITING: 'FETCH_PUBLIC_FLAGS_WAITING',
  FETCH_PUBLIC_FLAGS_SUCCESS: 'FETCH_PUBLIC_FLAGS_SUCCESS',
  FETCH_PUBLIC_FLAGS_FAIL: 'FETCH_PUBLIC_FLAGS_FAIL',
};
